from repositories.author_repository import create_author, get_author_by_name_and_country
from repositories.book_repository import create_book, get_book_by_isbn, get_all_books, get_all_books_of_author, get_all_books_of_bookstore, get_all_books_of_category, get_all_books_of_publisher, get_book_by_sales
from repositories.bookstore_repository import create_bookstore, get_bookstore_by_name_and_country, get_all_bookstore_having_book
from repositories.bookstore_shelf_repository import create_bookstore_shelf
from repositories.category_repository import create_category, get_category_by_name
from repositories.client_repository import create_client, get_client_by_email
from repositories.country_repository import create_country, get_country_by_identifier, get_all_countries
from repositories.depot_repository import create_depot, get_depot
from repositories.depot_stock_movement_repository import create_depot_stock_movement
from repositories.distributor_repository import create_distributor, get_distributor_by_name_and_country, get_distributors_with_book_stock
from repositories.order_book_repository import create_order_book, get_order_book_by_book_and_status, delete_order
from repositories.publisher_repository import create_publisher, get_publisher_by_name
from repositories.purchase_order_repository import create_purchase, get_all_purchases_of_distributor, get_all_purchases_of_bookstore, get_purchases_by_bookstore_and_status, get_purchases_by_distributor_and_status, get_purchase_by_distributor_status_and_bookstore
from repositories.shelf_stock_movement_repository import create_shelf_stock_movement