"""add check constraints to multiple tables

Revision ID: 2bb2f1ebe457
Revises: be3b01ac5ff2
Create Date: 2026-06-22 15:36:26.691682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2bb2f1ebe457'
down_revision: Union[str, Sequence[str], None] = 'be3b01ac5ff2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint(
        "ck_price",
        "book",
        "price >= 0"
    )
    op.create_check_constraint(
        "ck_quantity",
        "bookstore_shelf",
        "quantity >= 0"
    )
    op.create_check_constraint(
        "ck_email",
        "client",
        r"email ~ '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$'"
    )
    op.create_check_constraint(
        "ck_stock_quantity",
        "depot",
        "stock_quantity >= 0"
    )
    op.create_check_constraint(
        "ck_quantity",
        "order_book",
        "quantity >= 0"
    )
    op.create_check_constraint(
        "ck_total_price",
        "purchase_order",
        "total_price >= 0"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "ck_price",
        "book",
        type_="check"
    )
    op.drop_constraint(
        "ck_quantity",
        "bookstore_shelf",
        type_="check"
    )
    op.drop_constraint(
        "ck_email",
        "client",
        type_="check"
    )
    op.drop_constraint(
        "ck_stock_quantity",
        "depot",
        type_="check"
    )
    op.drop_constraint(
        "ck_quantity",
        "order_book",
        type_="check"
    )
    op.drop_constraint(
        "ck_total_price",
        "purchase_order",
        type_="check"
    )
    # ### end Alembic commands ###
