"""add all initial tables

Revision ID: acea13f549a1
Revises: 6a8a60eb7775
Create Date: 2026-06-17 16:27:14.355026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'acea13f549a1'
down_revision: Union[str, Sequence[str], None] = '6a8a60eb7775'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), sa.Identity(always=True), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('country',
    sa.Column('identifier', sa.String(length=2), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('vat', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('identifier'),
    sa.UniqueConstraint('name')
    )
    op.create_table('author',
    sa.Column('id', sa.Integer(), sa.Identity(always=True), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('country_identifier', sa.String(length=2), nullable=True),
    sa.ForeignKeyConstraint(['country_identifier'], ['country.identifier'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bookstore',
    sa.Column('id', sa.Integer(), sa.Identity(always=True), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('country_identifier', sa.String(length=2), nullable=False),
    sa.ForeignKeyConstraint(['country_identifier'], ['country.identifier'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('client',
    sa.Column('id', sa.Integer(), sa.Identity(always=True), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('country_identifier', sa.String(length=2), nullable=False),
    sa.ForeignKeyConstraint(['country_identifier'], ['country.identifier'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('distributor',
    sa.Column('id', sa.Integer(), sa.Identity(always=True), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('operating_country_identifier', sa.String(length=2), nullable=False),
    sa.ForeignKeyConstraint(['operating_country_identifier'], ['country.identifier'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('book',
    sa.Column('id', sa.Integer(), sa.Identity(always=True), nullable=False),
    sa.Column('isbn', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('publisher_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['author.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['publisher_id'], ['publisher.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('isbn')
    )
    op.create_table('purchase_order',
    sa.Column('id', sa.Integer(), sa.Identity(always=True), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'PACKAGED', 'SHIPPED', 'DELIVERED', 'CANCELLED', 'REFUNDED', name='status'), nullable=False),
    sa.Column('total_price', sa.Float(), nullable=True),
    sa.Column('order_date', sa.DateTime(), nullable=False),
    sa.Column('bookstore_id', sa.Integer(), nullable=False),
    sa.Column('distributor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bookstore_id'], ['bookstore.id'], ),
    sa.ForeignKeyConstraint(['distributor_id'], ['distributor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bookstore_shelf',
    sa.Column('id', sa.Integer(), sa.Identity(always=True), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('bookstore_id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ),
    sa.ForeignKeyConstraint(['bookstore_id'], ['bookstore.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('depot',
    sa.Column('id', sa.Integer(), sa.Identity(always=True), nullable=False),
    sa.Column('stock_quantity', sa.Integer(), nullable=True),
    sa.Column('distributor_id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ),
    sa.ForeignKeyConstraint(['distributor_id'], ['distributor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_book',
    sa.Column('id', sa.Integer(), sa.Identity(always=True), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['purchase_order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('depot_stock_movement',
    sa.Column('id', sa.Integer(), sa.Identity(always=True), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('comment', sa.String(length=200), nullable=True),
    sa.Column('depot_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['depot_id'], ['depot.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shelf_stock_movement',
    sa.Column('id', sa.Integer(), sa.Identity(always=True), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('comment', sa.String(length=200), nullable=True),
    sa.Column('bookstore_shelf_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bookstore_shelf_id'], ['bookstore_shelf.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shelf_stock_movement')
    op.drop_table('depot_stock_movement')
    op.drop_table('order_book')
    op.drop_table('depot')
    op.drop_table('bookstore_shelf')
    op.drop_table('purchase_order')
    op.drop_table('book')
    op.drop_table('distributor')
    op.drop_table('client')
    op.drop_table('bookstore')
    op.drop_table('author')
    op.drop_table('country')
    op.drop_table('category')
    # ### end Alembic commands ###
