"""add email, publication_date and more unique constraints

Revision ID: be3b01ac5ff2
Revises: acea13f549a1
Create Date: 2026-06-22 14:57:07.788565

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be3b01ac5ff2'
down_revision: Union[str, Sequence[str], None] = 'acea13f549a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('author', 'country_identifier',
               existing_type=sa.VARCHAR(length=2),
               nullable=False)
    op.create_unique_constraint('uk_author', 'author', ['name', 'country_identifier'])
    op.add_column('book', sa.Column('publication_date', sa.DateTime(), nullable=True))
    op.create_unique_constraint('uk_bookstore', 'bookstore', ['name', 'country_identifier'])
    op.add_column('client', sa.Column('email', sa.String(length=50), nullable=False))
    op.create_unique_constraint(None, 'client', ['email'])
    op.create_unique_constraint('uk_distributor', 'distributor', ['name', 'operating_country_identifier'])
    op.create_unique_constraint(None, 'publisher', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'publisher', type_='unique')
    op.drop_constraint('uk_distributor', 'distributor', type_='unique')
    op.drop_constraint(None, 'client', type_='unique')
    op.drop_column('client', 'email')
    op.drop_constraint('uk_bookstore', 'bookstore', type_='unique')
    op.drop_column('book', 'publication_date')
    op.drop_constraint('uk_author', 'author', type_='unique')
    op.alter_column('author', 'country_identifier',
               existing_type=sa.VARCHAR(length=2),
               nullable=True)
    # ### end Alembic commands ###
